/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.Analyst;

import Business.EcoSystem;
import UserInterface.Homepage.MainJFrame;
import java.awt.Color;
import java.awt.Font;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JPanel;

/**
 *
 * @author anirudh
 */
public class AnalyzeMarketJpanel extends javax.swing.JPanel {

    /**
     * Creates new form AnalyzeMarketJpanel
     */
    EcoSystem system;
    public AnalyzeMarketJpanel(EcoSystem system) {
        initComponents();
        this.system = system;
        
        //method for click-response action buttons
        ArrayList<JButton> buttonList = new ArrayList<>();
        buttonList.add(btnEmgServices);
        buttonList.add(btnFoodEnt);
        buttonList.add(btnRecEnt);
        buttonList.add(btnRentalEnterprises);
        buttonList.add(btnShoppingEnt);
        
        ActionListener buttonActionListener = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                JButton clickedButton = (JButton) e.getSource();
                for (JButton btn : buttonList) {
                    btn.setForeground(Color.BLACK); 
                    btn.setBackground(Color.DARK_GRAY);
                    Font originalFont = btn.getFont();
                    Font plainFont = originalFont.deriveFont(Font.PLAIN);
                    btn.setFont(plainFont);
                }
                clickedButton.setForeground(Color.red); 
                clickedButton.setBackground(Color.white);
                Font originalFont = clickedButton.getFont();
                Font boldFont = originalFont.deriveFont(Font.BOLD);
                clickedButton.setFont(boldFont);
            }
        };
        for (JButton btn : buttonList) {
        btn.addActionListener(buttonActionListener);
}
    }
    
    
    
    //method for adding gradient backdrop
    public static class jPanelGradient extends JPanel {
    protected void paintComponent(Graphics g) {
        Graphics2D g2d = (Graphics2D) g;
        int width = getWidth();
        int height = getHeight();

       //Color color1 = new Color(52, 143, 80);
        Color color1 = new Color(255, 153, 51);
        Color color2 = new Color(255, 102, 0);
        //Color color2 = new Color(86, 180, 211);
        GradientPaint gp = new GradientPaint(0, 0, color1, 180, height, color2);
        g2d.setPaint(gp);
        g2d.fillRect(0, 0, width, height);
    }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        btnFoodEnt = new javax.swing.JButton();
        btnRecEnt = new javax.swing.JButton();
        btnShoppingEnt = new javax.swing.JButton();
        btnEmgServices = new javax.swing.JButton();
        btnRentalEnterprises = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        jPanel2 = new jPanelGradient();

        jSplitPane1.setDividerLocation(200);

        jPanel1.setBackground(new java.awt.Color(102, 0, 0));

        btnFoodEnt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Icons/Food20 (1).png"))); // NOI18N
        btnFoodEnt.setText("Food Enterprise");
        btnFoodEnt.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Icons/Food20_filled.png"))); // NOI18N
        btnFoodEnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFoodEntActionPerformed(evt);
            }
        });

        btnRecEnt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Icons/Recreation (1).png"))); // NOI18N
        btnRecEnt.setText("Recreation Enterprise");
        btnRecEnt.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Icons/Recreation (2).png"))); // NOI18N
        btnRecEnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecEntActionPerformed(evt);
            }
        });

        btnShoppingEnt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Icons/Shoppong (1).png"))); // NOI18N
        btnShoppingEnt.setText("Shopping Enterprise");
        btnShoppingEnt.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Icons/Shoppong (2).png"))); // NOI18N
        btnShoppingEnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShoppingEntActionPerformed(evt);
            }
        });

        btnEmgServices.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Icons/Emergency (1).png"))); // NOI18N
        btnEmgServices.setText("Emergency Services");
        btnEmgServices.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Icons/Emergency (2).png"))); // NOI18N
        btnEmgServices.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmgServicesActionPerformed(evt);
            }
        });

        btnRentalEnterprises.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Icons/Rental (1).png"))); // NOI18N
        btnRentalEnterprises.setText("Rental Enterprise");
        btnRentalEnterprises.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Icons/Rental (2).png"))); // NOI18N
        btnRentalEnterprises.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRentalEnterprisesActionPerformed(evt);
            }
        });

        btnLogout.setBackground(new java.awt.Color(102, 102, 102));
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Icons/logoutNew20.png"))); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnLogout.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Icons/logout_filled20.png"))); // NOI18N
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnRecEnt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnFoodEnt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnShoppingEnt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEmgServices, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRentalEnterprises, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(34, 34, 34))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(btnFoodEnt)
                .addGap(67, 67, 67)
                .addComponent(btnRecEnt)
                .addGap(75, 75, 75)
                .addComponent(btnShoppingEnt)
                .addGap(85, 85, 85)
                .addComponent(btnEmgServices)
                .addGap(90, 90, 90)
                .addComponent(btnRentalEnterprises)
                .addGap(113, 113, 113)
                .addComponent(btnLogout)
                .addGap(77, 77, 77))
        );

        jSplitPane1.setLeftComponent(jPanel1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1289, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 798, Short.MAX_VALUE)
        );

        jSplitPane1.setRightComponent(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRecEntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecEntActionPerformed
        // TODO add your handling code here:
        AnalyzeRecreationEnterprise panel = new AnalyzeRecreationEnterprise(system);
        jSplitPane1.setRightComponent(panel);
    }//GEN-LAST:event_btnRecEntActionPerformed

    private void btnShoppingEntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShoppingEntActionPerformed
        // TODO add your handling code here:
        AnalyzeShoppingEnterprise panel = new AnalyzeShoppingEnterprise(system);
        jSplitPane1.setRightComponent(panel);
    }//GEN-LAST:event_btnShoppingEntActionPerformed

    private void btnEmgServicesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmgServicesActionPerformed
        // TODO add your handling code here:
        AnalyzeEmergencyServices panel = new AnalyzeEmergencyServices(system);
        jSplitPane1.setRightComponent(panel);
    }//GEN-LAST:event_btnEmgServicesActionPerformed

    private void btnRentalEnterprisesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRentalEnterprisesActionPerformed
        // TODO add your handling code here:
        AnalyzeRentalEnterprise panel = new AnalyzeRentalEnterprise(system);
        jSplitPane1.setRightComponent(panel);
        
    }//GEN-LAST:event_btnRentalEnterprisesActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        MainJFrame.changeScreen(MainJFrame.LandinPageJPanel);

    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnFoodEntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFoodEntActionPerformed
        // TODO add your handling code here:
        AnalzyeFoodEnterprise panel = new AnalzyeFoodEnterprise(system);
        jSplitPane1.setRightComponent(panel);
    }//GEN-LAST:event_btnFoodEntActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEmgServices;
    private javax.swing.JButton btnFoodEnt;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnRecEnt;
    private javax.swing.JButton btnRentalEnterprises;
    private javax.swing.JButton btnShoppingEnt;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables
}
