/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.Analyst;

import Business.EcoSystem;
import java.util.Arrays;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JPanel;

/**
 *
 * @author anirudh
 */
public class AnalyzeEmergencyServices extends javax.swing.JPanel {

    /**
     * Creates new form AnalyzeEmergencyServices
     */
    List<String> cities = Arrays.asList("New York", "Los Angeles", "Chicago", 
                                    "Houston", "Phoenix", "Philadelphia", 
                                    "San Antonio", "San Diego", "Dallas", 
                                    "San Jose");
    EcoSystem system;
    String targetCity = "New York";
    public AnalyzeEmergencyServices(EcoSystem system) {
        initComponents();
        fillComboBox();
        this.system = system;
        system.getMedicalEnterprise().performAnalysisForCity(system.getAppointments().getAppointmentList(), system.getHospitalDirectory().getHospitalList(), targetCity, SymptomAnalysis);
        system.getPoliceEnterprise().plotReportData(system.getReports().getReportList(), cities, PoliceReport);
    }
    
        public void fillComboBox()
    {
        
        
        jComboBox1.setModel(new DefaultComboBoxModel<String>(cities.toArray(new String[0])));
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        MedicalServicesJPanel = new AnalyzeMarketJpanel.jPanelGradient();
        jComboBox1 = new javax.swing.JComboBox<>();
        SymptomAnalysis = new javax.swing.JPanel();
        jPanel2 = new AnalyzeMarketJpanel.jPanelGradient();
        PoliceReport = new javax.swing.JPanel();

        jSplitPane1.setDividerLocation(400);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SymptomAnalysisLayout = new javax.swing.GroupLayout(SymptomAnalysis);
        SymptomAnalysis.setLayout(SymptomAnalysisLayout);
        SymptomAnalysisLayout.setHorizontalGroup(
            SymptomAnalysisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 745, Short.MAX_VALUE)
        );
        SymptomAnalysisLayout.setVerticalGroup(
            SymptomAnalysisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 313, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout MedicalServicesJPanelLayout = new javax.swing.GroupLayout(MedicalServicesJPanel);
        MedicalServicesJPanel.setLayout(MedicalServicesJPanelLayout);
        MedicalServicesJPanelLayout.setHorizontalGroup(
            MedicalServicesJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MedicalServicesJPanelLayout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(SymptomAnalysis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 132, Short.MAX_VALUE)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(125, 125, 125))
        );
        MedicalServicesJPanelLayout.setVerticalGroup(
            MedicalServicesJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MedicalServicesJPanelLayout.createSequentialGroup()
                .addGroup(MedicalServicesJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MedicalServicesJPanelLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MedicalServicesJPanelLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(SymptomAnalysis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(63, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(MedicalServicesJPanel);

        javax.swing.GroupLayout PoliceReportLayout = new javax.swing.GroupLayout(PoliceReport);
        PoliceReport.setLayout(PoliceReportLayout);
        PoliceReportLayout.setHorizontalGroup(
            PoliceReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 781, Short.MAX_VALUE)
        );
        PoliceReportLayout.setVerticalGroup(
            PoliceReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 356, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(187, 187, 187)
                .addComponent(PoliceReport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(330, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(PoliceReport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jSplitPane1.setRightComponent(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
       targetCity = jComboBox1.getSelectedItem().toString();
       system.getMedicalEnterprise().performAnalysisForCity(system.getAppointments().getAppointmentList(), system.getHospitalDirectory().getHospitalList(), targetCity, SymptomAnalysis);

       
    }//GEN-LAST:event_jComboBox1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MedicalServicesJPanel;
    private javax.swing.JPanel PoliceReport;
    private javax.swing.JPanel SymptomAnalysis;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables
}
