/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package Business.Enterprise.Shopping;

import Business.EcoSystem;
import Business.Organisation.Shop.Shop;
import Business.Organisation.Shop.ShoppingOrder;
import java.awt.BorderLayout;
import java.awt.Color;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JFrame;
import javax.swing.JPanel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PiePlot;
import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author anirudh
 */
public class ShopEnterprise {
    
    // revenue generated by different shops (pie chart)
    
    public static void analyzeAndPlotShopMarketShare(EcoSystem system, String city, JPanel targetPanel) {
    // [Previous steps to calculate total sales per shop and create the dataset]
    Map<Integer, Float> totalSalesPerShop = new HashMap<>();
    for (ShoppingOrder order : system.getShoppingOrders().getOrderList()) {
        Shop shop = findShopById(system, order.getShopId());
        if (shop != null && shop.getLocation().equals(city)) {
            float currentTotal = totalSalesPerShop.getOrDefault(order.getShopId(), 0f);
            totalSalesPerShop.put(order.getShopId(), currentTotal + order.getOrderTotal());
        }
    }

    // Step 2: Creating dataset for pie chart
    DefaultPieDataset dataset = new DefaultPieDataset();
    for (Map.Entry<Integer, Float> entry : totalSalesPerShop.entrySet()) {
        Shop shop = findShopById(system, entry.getKey());
        if (shop != null) {
            dataset.setValue(shop.getName(), entry.getValue());
        }
    }

    // Step 3: Generating the pie chart
    JFreeChart pieChart = ChartFactory.createPieChart(
        "Market Share of Shops in " + city,
        dataset,
        true,
        true,
        false
    );

    PiePlot plot = (PiePlot) pieChart.getPlot();
    plot.setSectionPaint(1, new Color(169, 169, 169)); // Example to set color

    ChartPanel chartPanel = new ChartPanel(pieChart);
    chartPanel.setPreferredSize(new java.awt.Dimension(840, 308)); // Set the preferred size

    // Update the target panel with the chart
    targetPanel.removeAll();
    targetPanel.setLayout(new BorderLayout());
    targetPanel.add(chartPanel, BorderLayout.CENTER);

    targetPanel.revalidate();
    targetPanel.repaint();
}


    private static Shop findShopById(EcoSystem system, int shopId) {
    ArrayList<Shop> shops = system.getShopDirectory().getShopList();

    // Loop through the list of shops to find the shop with the matching ID
    for (Shop shop : shops) {
        if (shop.getId() == shopId) {
            return shop; // Return the found shop
        }
    }
    return null;

    }
    
}
